In [1]:
import tensorflow as tf

In [81]:
#(a-b)^2=a^2+b^2-2ab
a=5
b=2

with tf.name_scope("lab1_assgn1"):
    with tf.name_scope("Scope_A"):
        x = tf.multiply(a, a)
        y = tf.multiply(b, b)
    with tf.name_scope("Scope_B"):
        z = tf.multiply(2, a)
        h = tf.multiply(z, b)

with tf.name_scope("Scope_C"):
    d = tf.add(x, y)
    s = tf.subtract(d, h)



with tf.Session() as sess:
    writer = tf.summary.FileWriter("/tmp/tboard/sam", sess.graph)
    print(sess.run(s))
    writer.close()

9


In [11]:
import numpy as np


In [23]:
import numpy as np
a=np.array([1,2,3])
b=np.array([3,4,5])
c=tf.reduce_mean(a)
d=tf.reduce_mean(b)

with tf.Session() as sess:
    writer = tf.summary.FileWriter("/tmp/tboard/output_a", sess.graph)
    print(sess.run(c))
    print(sess.run(d))
    writer.close()



2
4


In [50]:
import tensorflow as tf
import tensorflow as tf
x=tf.constant([1.0,2.0,3.0,4.0],shape=[1,4],name='x')
y=tf.constant([5.0,6.0,7.0,8.0],shape=[1,4],name='y')
with tf.name_scope("mean"):
    with tf.name_scope("mean_x_y"):
        x1=tf.reduce_mean(x)
        y1=tf.reduce_mean(y)
        sess=tf.Session()
    print(sess.run(x1))
    print(sess.run(y1))
with tf.name_scope("variance"):
    with tf.name_scope("scope_sub1"):
        a=tf.subtract(x,x1)
        sess1=tf.Session()
    print(sess1.run(a))
    with tf.name_scope("scope_sub2"):
        b=tf.subtract(y,y1)
        sess2=tf.Session()
    print(sess2.run(b))
    with tf.name_scope("scope_square"):
        a1=tf.multiply(a,a)
        sess3=tf.Session()
    print(sess3.run(a1))
    with tf.name_scope("scope_summation"):
        var=tf.reduce_sum(a1)
        sess4=tf.Session()
    print(sess4.run(var))
with tf.name_scope("covariance"):
    with tf.name_scope("multiplication"):
        mul1=tf.multiply(a,b)
        sess5=tf.Session()
    print(sess5.run(mul1))
    with tf.name_scope("scope_summation2"):
        covar=tf.reduce_sum(mul1)
        sess6=tf.Session()
    print(sess6.run(covar))

2.5
6.5
[[-1.5 -0.5  0.5  1.5]]
[[-1.5 -0.5  0.5  1.5]]
[[ 2.25  0.25  0.25  2.25]]
5.0
[[ 2.25  0.25  0.25  2.25]]
5.0


In [72]:
# mean of x and y
import tensorflow as tf

with tf.name_scope("var"):
    with tf.name_scope("mean_x"):
        a=tf.constant([25.0,27.0,26.2,27.32],shape=[1,4],name='a')
        b=tf.constant([7.0,9.0,10.0,8.0],shape=[1,4],name='b')
        x=tf.reduce_mean(a)
        sess=tf.Session()
    print(sess.run(x))
    
with tf.name_scope("mean_y"):
        y=tf.reduce_mean(b)
        sess=tf.Session()
print(sess.run(y))

    

26.38
8.5


In [69]:
#variance
d=tf.subtract(a,x)
sess=tf.Session()
print(sess.run(d ))

e=tf.square(d)
f=tf.reduce_sum(e)
sess=tf.Session()
print(sess.run(f))


[[-1.38000107  0.61999893 -0.18000031  0.93999863]]
3.2048


In [71]:
#covariance,value of c,value of m
with tf.name_scope("covariance"):
    g=tf.subtract(b,y)
    sess=tf.Session()
    g=tf.multiply(d,g)
    h=tf.reduce_sum(g)
print(sess.run(h))

with tf.name_scope("value_of_c"):
    j=tf.divide(h,f)
print(sess.run(j))

with tf.name_scope("value_m"):
    i=tf.multiply(j,x)
    k=tf.subtract(y,i)
print(sess.run(j))

1.64
0.511733
0.511733


In [80]:
#(a^3+b^3)=(a+b)(a^2-ab+b^2)
import tensorflow as tf
var1=tf.constant(4)
var2=tf.constant(2)
with tf.name_scope("MyOperationGroup"):
    with tf.name_scope("Scope_A"):
        a = tf.multiply(var1,var1)
        b = tf.multiply(var2,var2)  
        with tf.name_scope("Scope_B"):
            c = tf.add(a, b, name="And_These_ones")
            d = tf.multiply(var1, var2, name="Multiply_these_numbers")

    with tf.name_scope("Scope_C"):
         e=tf.subtract(c,d, name="subtrating")
        f=tf.add(var1,var2)
   
    with tf.name_scope("Scope_D"):
        g = tf.multiply(f,e)


    with tf.Session() as sess:
        writer = tf.summary.FileWriter("/tmp/tboard/output_la", sess.graph)
    print(sess.run(g))
    writer.close()

72
